added Cython as dependency  in appveyor
added the dependency due to the following appveyor error
ModuleNotFoundError: No module named 'Cython'
FileNotFoundError: [WinError 2] The system cannot find the file specified